[2022-12-21 14:21:07,676] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [queued]>
[2022-12-21 14:21:07,686] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [queued]>
[2022-12-21 14:21:07,687] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-21 14:21:07,687] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-21 14:21:07,687] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-21 14:21:07,700] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): load_to_gcs_task> on 2022-12-20 10:00:00+00:00
[2022-12-21 14:21:07,704] {standard_task_runner.py:52} INFO - Started process 590 to run task
[2022-12-21 14:21:07,708] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fireflow_dag', 'load_to_gcs_task', 'scheduled__2022-12-20T10:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/fireflow_batch_dag.py', '--cfg-path', '/tmp/tmpuqb313ri', '--error-file', '/tmp/tmp179sk9um']
[2022-12-21 14:21:07,710] {standard_task_runner.py:77} INFO - Job 59: Subtask load_to_gcs_task
[2022-12-21 14:21:07,767] {logging_mixin.py:109} INFO - Running <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [running]> on host 78bd7b303d21
[2022-12-21 14:21:07,869] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fireflow_dag
AIRFLOW_CTX_TASK_ID=load_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-20T10:00:00+00:00
[2022-12-21 14:21:08,017] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 53, in load_data_to_gcs
    client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 128, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 318, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 266, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 285, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File ../../credentials/fireflow-creds.json was not found.
[2022-12-21 14:21:08,168] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=fireflow_dag, task_id=load_to_gcs_task, execution_date=20221220T100000, start_date=20221221T142107, end_date=20221221T142108
[2022-12-21 14:21:08,227] {standard_task_runner.py:92} ERROR - Failed to execute job 59 for task load_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 53, in load_data_to_gcs
    client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 128, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 318, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 266, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client.py", line 285, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File ../../credentials/fireflow-creds.json was not found.
[2022-12-21 14:21:08,405] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-21 14:21:08,453] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-21 15:50:27,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [queued]>
[2022-12-21 15:50:27,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [queued]>
[2022-12-21 15:50:27,800] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-21 15:50:27,800] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-21 15:50:27,801] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-21 15:50:27,817] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): load_to_gcs_task> on 2022-12-20 10:00:00+00:00
[2022-12-21 15:50:27,841] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fireflow_dag', 'load_to_gcs_task', 'scheduled__2022-12-20T10:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/fireflow_batch_dag.py', '--cfg-path', '/tmp/tmp9sbrd_2v', '--error-file', '/tmp/tmpchus7__9']
[2022-12-21 15:50:27,834] {standard_task_runner.py:52} INFO - Started process 108 to run task
[2022-12-21 15:50:27,849] {standard_task_runner.py:77} INFO - Job 4: Subtask load_to_gcs_task
[2022-12-21 15:50:28,150] {logging_mixin.py:109} INFO - Running <TaskInstance: fireflow_dag.load_to_gcs_task scheduled__2022-12-20T10:00:00+00:00 [running]> on host ffb0f01832af
[2022-12-21 15:50:28,311] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fireflow_dag
AIRFLOW_CTX_TASK_ID=load_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-20T10:00:00+00:00
[2022-12-21 15:50:31,775] {python.py:175} INFO - Done. Returned value was: None
[2022-12-21 15:50:31,788] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fireflow_dag, task_id=load_to_gcs_task, execution_date=20221220T100000, start_date=20221221T155027, end_date=20221221T155031
[2022-12-21 15:50:31,818] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-21 15:50:31,856] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
